name: Android Build Capability

on:
  workflow_call:
    secrets:
      key_password:
        required: true
      keystore_password:
        required: true
      android_keystore_base64:
        required: true

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      app_name: ${{ steps.meta.outputs.app_name }}
      app_version: ${{ steps.meta.outputs.app_version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Android
        id: meta
        uses: cvch29/challenge-templates/.github/actions/mobile/setup/android@main

      - name: Build Android App
        uses: cvch29/challenge-templates/.github/actions/mobile/build/android@main
        with:
          keystore_path: android-keystore.jks
          store_password: ${{ secrets.keystore_password }}
          key_alias: keyAlias
          key_password: ${{ secrets.key_password }}
          keystore_base64: ${{ secrets.android_keystore_base64 }}

      - name: Remote Config
        uses: cvch29/challenge-templates/.github/actions/mobile/config/remote-config@main

      - name: Upload artifacts
        uses: cvch29/challenge-templates/.github/actions/shared/artifact_manage@main