name: Android Quality Capability

on:
  workflow_call:

jobs:

  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sonar Analysis
        uses: cvch29/challenge-templates/.github/actions/security_quality/sast/sonar@main