name: Mobile PR Validation

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:

  unit_test:
    uses: cvch29/platform-workflows/.github/workflows/mobile-unit-test.yml@main

  security:
    uses: cvch29/platform-workflows/.github/workflows/mobile-security.yml@main

  quality:
    uses: cvch29/platform-workflows/.github/workflows/mobile-quality.yml@main