name: 'Mobile Android — Build'

on:
  workflow_call:
    inputs:
      technology:
        description: 'react-native | native'
        type: string
        required: true
        default: 'native'
      app-name:
        type: string
        required: true
      app-version:
        type: string
        required: true
      java-version:
        type: string
        required: false
        default: '17'
      sign:
        type: boolean
        required: false
        default: true

      keystore-base64:
        type: string
        required: false
      keystore-password:
        type: string
        required: false
      keystore-alias:
        type: string
        required: false
      command:
        type: string
        required: false
        default: assembleRelease
    secrets:
      keystore-base64:
        required: false
      keystore-password:
        required: false
      keystore-alias:
        required: false
      keystore-path:
        required: false
jobs:
  build:
    name: Build
    runs-on:
      group: dso-linux
    env:
      GRADLE_USER_HOME: /tmp/gradle-${{ github.run_id }}-${{ github.run_attempt }}
      METRO_CACHE: /tmp/metro-cache
      NODE_OPTIONS: --max-old-space-size=8192
    container:
      image: localhost:5000/android:35-gradle7.3-jdk17
      options: --cpus 8 -m 16g
      volumes:
        - /opt/cache/yarn:/opt/yarn
        - /opt/cache/gradle/modules-2:/opt/gradle-shared/modules-2
        - /opt/cache/gradle/transforms-3:/opt/gradle-shared/transforms-3
        - /opt/cache/gradle/build-cache-1:/opt/gradle-shared/build-cache-1
        - /opt/cache/gradle/wrapper:/opt/gradle-shared/wrapper
        - /opt/cache/metro:/tmp/metro-cache
        - /opt/cache/cxx:/workspace/android/.cxx
    steps:
      - uses: actions/checkout@v4

      # - name: Restore shared gradle cache
      #   run: |
      #     mkdir -p $GRADLE_USER_HOME/caches
      #     mkdir -p $GRADLE_USER_HOME/wrapper

      #     ln -snf /opt/gradle-shared/modules-2 \
      #       $GRADLE_USER_HOME/caches/modules-2

      #     ln -snf /opt/gradle-shared/transforms-3 \
      #       $GRADLE_USER_HOME/caches/transforms-3

      #     ln -snf /opt/gradle-shared/build-cache-1 \
      #       $GRADLE_USER_HOME/caches/build-cache-1

      #     ln -snf /opt/gradle-shared/wrapper \
      #       $GRADLE_USER_HOME/wrapper/dists

      - name: Install Dependencies
        if: ${{ inputs.technology == 'react-native' }}
        uses: cvch29/platform-actions/.github/actions/tooling/node@main
        with:
          working-directory: .

      - name: Signing Keystore
        if: ${{ inputs.sign }}
        uses: cvch29/platform-actions/.github/actions/shared-v2/signing-keystore@main
        with:
          keystore-base64: ${{ secrets.keystore_base64 }}
          keystore-path: ${{ secrets.keystore-path }}

      - name: Android build
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/build@main
        with:
          command: ${{ inputs.command }}
          keystore-alias: ${{ inputs.keystore-alias }}
          keystore-password: ${{ secrets.keystore-password }}
          keystore-path: ${{ secrets.keystore-path }}

      - name: Generate SBOM
        uses: cvch29/platform-actions/.github/actions/governance/sbom@main
        with:
          artifact-path: .
          upload-artifact: true

      - name: Artifact Management
        uses: cvch29/platform-actions/.github/actions/shared/artifact-manage@main
        with:
          app_name: ${{ inputs.app-name }}
          app_version: ${{ inputs.app-version }}
          path: android/app/build
          pattern: |
            outputs/apk/release/*.apk
            outputs/bundle/release/*.aab
            outputs/remote-config/config.json
            reports/profile/*.html
          name: android-release-files
          retention-days: 1
          if-no-files-found: warn
          compression-level: 6
          upload_path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
            android/remote-config/*.json
            android/build/reports/profile/*.html