name: 'Mobile Android — Release'

on:
  workflow_call:
    inputs:
      technology:
        description: 'react-native | native'
        type: string
        required: true
      android-channel:
        type: string
        required: false
        default: 'play-internal'
      package-manager:
        type: string
        required: false
        default: 'yarn'
      gradle-build-path:
        type: string
        default: app/build.gradle.kts
      environment:
        type: string
        default: dev
      keystore_path:
        type: string
        default: android-keystore.jks
      flavor:
        type: string
        default: ''
      command:
        type: string
        default: assembleRelease
      enable-android:
        type: boolean
        default: true
      enable-ios:
        type: boolean
        default: false
    secrets:
      keystore-base64:
        required: false
      keystore-password:
        required: false
      keystore-alias:
        required: false
      keystore-path:
        required: false
      github-token:
        required: true

jobs:
  # security:
  #   uses: cvch29/platform-workflows/.github/workflows/mobile-android-security.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #   permissions:
  #     contents: read
  #     security-events: write
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.setup-android.outputs.app-version }}
      app-name: ${{ steps.setup-android.outputs.app-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        id: setup-android
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-gradle-path: ${{ inputs.gradle-build-path }}
          
  build_android:
    if: success() && (inputs.enable-android == true)
    needs: setup
    name: Build Android
    uses: cvch29/platform-workflows/.github/workflows/mobile-android-build.yml@main
    with:
      app-name: ${{ needs.setup.outputs.app-name }}
      command: ${{ inputs.command }}
      app-version: ${{ needs.setup.outputs.app-version }}
      # build-type: release
      # flavor: ${{ inputs.flavor }}
      technology: ${{ inputs.technology }}
      sign: false
    secrets:
      keystore-base64: ${{ secrets.keystore-base64 }}
      keystore-password: ${{ secrets.keystore-password }}
      keystore-alias: ${{ secrets.keystore-alias }}
      keystore-path: ${{ secrets.keystore-path }}
  # quality-gate:
  #   needs: build
  #   uses: cvch29/platform-workflows/.github/workflows/shared-quality-gates.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #     environment: ${{ inputs.channel == 'play-production' && 'prod' || 'staging' }}
  #     require-sbom: true
  #     require-sast: true
  #     require-sca: true

  # distribute:
  #   name: Tag & Distribute
  #   needs: [build, quality-gate]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   outputs:
  #     version: ${{ steps.version.outputs.version }}
  #   steps:
  #     - uses: cvch29/platform-actions/.github/actions/shared-v2/checkout@main
  #       with:
  #         fetch-depth: 0
  #     - uses: cvch29/platform-actions/.github/actions/shared-v2/artifact-download@main
  #       with:
  #         name: release-artifact.zip
  #     - id: version
  #       uses: cvch29/platform-actions/.github/actions/intelligence/versioning@main
  #     - uses: cvch29/platform-actions/.github/actions/domains-v2/mobile/android/distribute@main
  #       with:
  #         artifact-path: ${{ needs.build.outputs.artifact-path }}
  #         channel: ${{ inputs.channel }}
  #         release-notes: "Release ${{ steps.version.outputs.version }}"
  #         firebase-app-id: ${{ inputs.firebase-app-id }}
  #         google-play-service-account-json: ${{ secrets.google-play-service-account-json }}
  #         package-name: ${{ inputs.package-name }}
  #     - if: always()
  #       uses: cvch29/platform-actions/.github/actions/governance/audit-log@main
  #       with:
  #         event-type: release
  #         environment: ${{ inputs.channel == 'play-production' && 'prod' || 'staging' }}
  #         outcome: ${{ job.status }}
  #         app-name: ${{ inputs.app-name }}
  #         metadata: '{"channel":"${{ inputs.channel }}","version":"${{ steps.version.outputs.version }}"}'
