name: 'Mobile iOS — Build'

on:
  workflow_call:
    inputs:
      technology:
        description: 'react-native | native'
        type: string
        required: true
        default: 'native'
      app-name:
        type: string
        required: true
      app-version:
        type: string
        required: true
      scheme:
        type: string
        required: true
      workspace:
        type: string
        required: false
        default: ''
      bundle-id:
        type: string
        required: true
      export-method:
        description: 'app-store | ad-hoc | enterprise'
        type: string
        required: false
        default: 'app-store'
      p12-file:
        type: string
        required: false
        default: ios-certificate.p12
    # outputs:
    #   ipa-path:
    #     value: ${{ jobs.build.outputs.ipa-path }}
    secrets:
      p12-base64:
        required: true
      p12-password:
        required: true
      provisioning-profile-base64:
        required: true

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest
    permissions:
      contents: read
    # outputs:
    #   ipa-path: ${{ steps.build.outputs.ipa-path }}
    steps:
      - uses: cvch29/platform-actions/.github/actions/shared-v2/checkout@main

      - name: Setup Keychain
        id: setup-keychain
        uses: cvch29/platform-actions/.github/actions/shared-v2/setup-keychain@main
        with:
          certificate-base64: ${{ secrets.p12-base64 }}
          certificate-file: ${{ inputs.p12-file }}
          # keystore-base64: ${{ secrets.keystore-base64 }}
          # keystore-path: ${{ secrets.keystore-file }}

      - name: Validate P12 Private Key
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/validate-private-key-p12@main
        with:
          p12-base64: ${{ secrets.p12-base64 }}
          p12-password: ${{ secrets.p12-password }}
          
      - name: Mostrar configuración de compilación
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/xcode-build-settings@main
        with:
          scheme: ${{ inputs.scheme }}
          configuration: ${{ inputs.configuration }}
          working-directory: "ios"

      - name: Definir perfil de aprovisionamiento
        if: ${{ inputs.provisioning-profile-base64 != '' }}
        run: |
          echo "PROFILE_NAME=$(security cms -D -i provisioning-profile.mobileprovision | plutil -extract 'UUID' xml1 -o - - | xmllint --xpath 'string(//plist/string)' -)" >> $GITHUB_ENV
        
      - name: Definir tipo de perfil de aprovisionamiento
        if: ${{ inputs.provisioning-profile-base64 != '' }}
        run: |
          PROFILE_TYPE=$(security cms -D -i provisioning-profile.mobileprovision | plutil -extract 'Entitlements' xml1 -o - - | xmllint --xpath 'string(//plist/dict/key[.="com.apple.developer.team-identifier"]/following-sibling::string[1])' -)
          echo "PROFILE_TYPE=$PROFILE_TYPE" >> $GITHUB_ENV
          echo "EXPORT_TYPE=$PROFILE_TYPE" >> $GITHUB_ENV

      - name: Descargar perfil de aprovisionamiento
        # if: ${{ inputs.provisioning-profile-base64 != '' }}
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/apple-download-provisioning-profile@main
        with:
          apple-api-key-id: ${{ secrets.apple-api-key-id }}
          apple-api-issuer-id: ${{ secrets.apple-api-key-issuer-id }}
          apple-api-key-content: ${{ secrets.apple-api-key-content }}
          profile-name: ${{ env.PROFILE_NAME }}
          app-identifier: ${{ inputs.bundle-id }}
          team-id: ${{ secrets.apple-team-id }}

      - name: Validar perfil de aprovisionamiento
        # if: ${{ inputs.provisioning-profile-base64 != '' }}
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/validate-provisioning-profile@main
        with:
          prov-profile-path: provisioning-profile.mobileprovision
          validate-cer: true
          fingerprint: ${{ secrets.p12-fingerprint }}

      - name: Instalar llave privada de apple
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/install-apple-private-key-p12@main
        with:
          p12-base64: ${{ secrets.p12-base64 }}
          p12-password: ${{ secrets.p12-password }}

      # - name: Instalar perfil de aprovisionamiento
      #   # if: ${{ inputs.provisioning-profile-base64 != '' }}
      #   uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/install-apple-provisioning-profile@main
      #   with:
      #     provisioning-profile-base64: ${{ secrets.provisioning-profile-base64 }}
      #     bundle-id: ${{ inputs.bundle-id }}

      - name: Install Dependencies
        if: ${{ inputs.technology == 'react-native' }}
        uses: cvch29/platform-actions/.github/actions/tooling/node@main
        with:
          working-directory: .
        
      - name: Configurar proyecto
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/xcode-configure-settings@main
        with:
          project: ${{ inputs.project }}
          target: ${{ inputs.target }}
          options: |
            PROVISIONING_PROFILE_SPECIFIER=${{ env.PROFILE_NAME }}
            DEVELOPMENT_TEAM=${{ secrets.apple-team-id }}
            CODE_SIGN_IDENTITY="Apple Distribution"
            CODE_SIGN_STYLE="Manual"
            CODE_SIGNING_REQUIRED=YES
            OTHER_CODE_SIGN_FLAGS=--keychain=${{ env.KEYCHAIN_PATH }}
          configuration: ${{ inputs.configuration }}

      # - name: Actualizar versión
      #   uses: cvch29/platform-actions/.github/actions/domains-v2/mobile/ios/build@main
      #   with:
      #     scheme: ${{ inputs.scheme }}
      #     workspace: ${{ inputs.workspace }}
      #     export-method: ${{ inputs.export-method }}
      #     options: |
      #       MARKETING_VERSION=${{ inputs.app-version }}
      #       CURRENT_PROJECT_VERSION=${{ inputs.app-version }}


      # - name: Configurar Proyecto para IxGuard
      #   if: ${{ env.IXGUARD_ENABLED == 'true' }}
      #   uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/xcode-configure-ixguard-toolchain@main
      #   with:
      #     workspace: ${{ inputs.workspace }}
      #     scheme: ${{ inputs.scheme }}
      #     target: ${{ inputs.target }}

      - name: Configurar IxGuard Toolchain
        if: ${{ env.IXGUARD_ENABLED == 'true' }}
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/xcode-configure-ixguard-toolchain@main
        with:
          workspace: ${{ inputs.workspace }}
          scheme: ${{ inputs.scheme }}
          target: ${{ inputs.target }}

      - name: Build iOS
        id: build
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/fastlane-generate-archive@main
        with:
          scheme: ${{ inputs.scheme }}
          workspace: ${{ inputs.workspace }}
          configuration: ${{ inputs.configuration }}

      - name: Ofuscar .archive con IxGuard
        if: ${{ env.IXGUARD_ENABLED == 'true' }}
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/ixguard-obfuscate@main
        with:
          archive: ${{ steps.build.outputs.archive-path }}
          configuration: ${{ inputs.configuration }}
          license-base64: ${{ secrets.ixguard-license-key }}

      - name: Exportar .ipa
        if: ${{ env.IXGUARD_ENABLED == 'true' }}
        uses: cvch29/platform-actions/.github/actions/domains/mobile/ios/config/fastlane-export-archive@main
        with:
          scheme: ${{ inputs.scheme }}
          workspace: ${{ inputs.workspace }}
          archive: ${{ steps.build.outputs.archive-path }}
          app-identifier: ${{ inputs.bundle-id }}
          prov-profile: ${{ env.PROFILE_NAME }}

      - name: Artifact Management
        uses: cvch29/platform-actions/.github/actions/shared/artifact-manage@main
        with:
          app_name: ${{ inputs.app-name }}
          app_version: ${{ inputs.app-version }}
          path: app
          pattern: |
            build/outputs/apk/release/*.apk
            build/outputs/bundle/release/*.aab
            build/outputs/remote-config/config.json
            build/reports/profile/*.html
          name: android-release-files
          retention-days: 1
          if-no-files-found: warn
          compression-level: 6
          upload_path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/bundle/release/*.aab
            app/remote-config/*.json
            app/build/reports/profile/*.html
            app/gradle.lockfile

      # - name: Upload Artifact
      #   uses: cvch29/platform-actions/.github/actions/shared-v2/artifact-upload@main
      #   with:
      #     name: ios-ipa-${{ inputs.app-name }}
      #     path: ${{ steps.build.outputs.ipa-path }}
      #     retention-days: 30
