name: 'Mobile Android — Release'

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true
      channel:
        description: 'firebase | play-internal | play-alpha | play-beta | play-production'
        type: string
        required: true
      flavor:
        type: string
        required: false
        default: ''
      package-name:
        type: string
        required: false
        default: ''
      firebase-app-id:
        type: string
        required: false
        default: ''
      gradle-build-path:
        type: string
        default: app/build.gradle.kts
    outputs:
      version:
        value: ${{ jobs.distribute.outputs.version }}
    secrets:
      keystore-base64:
        required: true
      keystore-password:
        required: true
      key-alias:
        required: true
      key-password:
        required: true
      firebase-service-account:
        required: false
      google-play-service-account-json:
        required: false
      github-token:
        required: true

jobs:
  # security:
  #   uses: cvch29/platform-workflows/.github/workflows/mobile-android-security.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #   permissions:
  #     contents: read
  #     security-events: write
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.setup_android.outputs.app_version }}
      app_name: ${{ steps.setup_android.outputs.app_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        id: setup_android
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-gradle-path: ${{ inputs.gradle-build-path }}
  # build:
  #   # needs: security
  #   uses: cvch29/platform-workflows/.github/workflows/mobile-android-build.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #     build-type: release
  #     flavor: ${{ inputs.flavor }}
  #     sign: true
  #   secrets:
  #     keystore-base64: ${{ secrets.keystore-base64 }}
  #     keystore-password: ${{ secrets.keystore-password }}
  #     key-alias: ${{ secrets.key-alias }}
  #     key-password: ${{ secrets.key-password }}


  build:
    name: Build
    needs: setup
    runs-on:
      group: dso-linux

    env:
      GRADLE_USER_HOME: /tmp/gradle-${{ github.run_id }}-${{ github.run_attempt }}
      # Metro cache
      METRO_CACHE: /tmp/metro-cache

      # Node memory (IMPORTANTE)
      NODE_OPTIONS: --max-old-space-size=8192

    container:
      image: localhost:5000/android:35-gradle7.3-jdk17
      options: --cpus 8 -m 16g
      volumes:
        # Yarn cache
        - /opt/cache/yarn:/opt/yarn
        # Shared gradle dependency cache
        - /opt/cache/gradle/modules-2:/opt/gradle-shared/modules-2
        # Shared transforms cache
        - /opt/cache/gradle/transforms-3:/opt/gradle-shared/transforms-3
        # Shared build cache
        - /opt/cache/gradle/build-cache-1:/opt/gradle-shared/build-cache-1
        # Shared wrapper cache
        - /opt/cache/gradle/wrapper:/opt/gradle-shared/wrapper
        # Metro cache
        - /opt/cache/metro:/tmp/metro-cache
        # C++ cache (RN native libs)
        - /opt/cache/cxx:/workspace/android/.cxx
    steps:
      - uses: actions/checkout@v4

      - name: Restore shared gradle cache
        run: |
          mkdir -p $GRADLE_USER_HOME/caches
          mkdir -p $GRADLE_USER_HOME/wrapper

          ln -snf /opt/gradle-shared/modules-2 \
            $GRADLE_USER_HOME/caches/modules-2

          ln -snf /opt/gradle-shared/transforms-3 \
            $GRADLE_USER_HOME/caches/transforms-3

          ln -snf /opt/gradle-shared/build-cache-1 \
            $GRADLE_USER_HOME/caches/build-cache-1

          ln -snf /opt/gradle-shared/wrapper \
            $GRADLE_USER_HOME/wrapper/dists

      - name: Install Dependencies
        uses: cvch29/platform-actions/.github/actions/tooling-v2/node@main
        with:
          working-directory: .

      - name: Android build
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/build@main
        with:
          keystore_path: ${{ inputs.keystore_path }}
          store_password: ${{ secrets.keystore_password }}
          key_alias: ${{ inputs.key_alias }}
          key_password: ${{ secrets.key_password }}
          keystore_base64: ${{ secrets.android_keystore_base64 }}

      - name: Artifact Management
        uses: cvch29/platform-actions/.github/actions/shared/artifact-manage@main
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          path: android/app/build
          pattern: |
            outputs/apk/release/*.apk
            outputs/bundle/release/*.aab
            outputs/remote-config/config.json
            reports/profile/*.html
          name: android-release-files
          retention-days: 1
          if-no-files-found: warn
          compression-level: 6
          upload_path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
            android/remote-config/*.json
            android/build/reports/profile/*.html


  # quality-gate:
  #   needs: build
  #   uses: cvch29/platform-workflows/.github/workflows/shared-quality-gates.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #     environment: ${{ inputs.channel == 'play-production' && 'prod' || 'staging' }}
  #     require-sbom: true
  #     require-sast: true
  #     require-sca: true

  # distribute:
  #   name: Tag & Distribute
  #   needs: [build, quality-gate]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   outputs:
  #     version: ${{ steps.version.outputs.version }}
  #   steps:
  #     - uses: cvch29/platform-actions/.github/actions/shared-v2/checkout@main
  #       with:
  #         fetch-depth: 0
  #     - uses: cvch29/platform-actions/.github/actions/shared-v2/artifact-download@main
  #       with:
  #         name: release-artifact.zip
  #     - id: version
  #       uses: cvch29/platform-actions/.github/actions/intelligence/versioning@main
  #     - uses: cvch29/platform-actions/.github/actions/domains-v2/mobile/android/distribute@main
  #       with:
  #         artifact-path: ${{ needs.build.outputs.artifact-path }}
  #         channel: ${{ inputs.channel }}
  #         release-notes: "Release ${{ steps.version.outputs.version }}"
  #         firebase-app-id: ${{ inputs.firebase-app-id }}
  #         google-play-service-account-json: ${{ secrets.google-play-service-account-json }}
  #         package-name: ${{ inputs.package-name }}
  #     - if: always()
  #       uses: cvch29/platform-actions/.github/actions/governance/audit-log@main
  #       with:
  #         event-type: release
  #         environment: ${{ inputs.channel == 'play-production' && 'prod' || 'staging' }}
  #         outcome: ${{ job.status }}
  #         app-name: ${{ inputs.app-name }}
  #         metadata: '{"channel":"${{ inputs.channel }}","version":"${{ steps.version.outputs.version }}"}'
