name: 'Mobile React Native — Release'

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true
      platforms:
        description: 'android | ios | both'
        type: string
        required: false
        default: 'android'
      android-channel:
        type: string
        required: false
        default: 'play-internal'
      package-manager:
        type: string
        required: false
        default: 'yarn'
    outputs:
      version:
        value: ${{ jobs.tag.outputs.version }}
    secrets:
      android-keystore-base64:
        required: false
      android-keystore-password:
        required: false
      android-key-alias:
        required: false
      android-key-password:
        required: false
      github-token:
        required: true

jobs:
  security:
    uses: cvch29/platform-workflows/.github/workflows/shared-security-scan.yml@main
    with:
      app-name: ${{ inputs.app-name }}
      language: javascript
      run-codeql: true
      run-sca: true
      run-secrets: true
      run-sast: true
    permissions:
      contents: read
      security-events: write

  build-android:
    if: inputs.platforms == 'android' || inputs.platforms == 'both'
    needs: security
    uses: cvch29/platform-workflows/.github/workflows/mobile-android-build.yml@main
    with:
      app-name: ${{ inputs.app-name }}
      build-type: release
      sign: true
    secrets:
      keystore-base64: ${{ secrets.android-keystore-base64 }}
      keystore-password: ${{ secrets.android-keystore-password }}
      key-alias: ${{ secrets.android-key-alias }}
      key-password: ${{ secrets.android-key-password }}

  quality-gate:
    needs: [build-android]
    if: always() && needs.build-android.result != 'failure'
    uses: cvch29/platform-workflows/.github/workflows/shared-quality-gates.yml@main
    with:
      app-name: ${{ inputs.app-name }}
      environment: staging
      require-sbom: true

  tag:
    name: Tag Release
    needs: quality-gate
    uses: cvch29/platform-workflows/.github/workflows/shared-release-tag.yml@main
    with:
      app-name: ${{ inputs.app-name }}
    secrets:
      github-token: ${{ secrets.github-token }}
