name: 'Mobile React Native — Release'

on:
  workflow_call:
    inputs:
      technology:
        description: 'react-native | native'
        type: string
        required: true
      android-channel:
        type: string
        required: false
        default: 'play-internal'
      package-manager:
        type: string
        required: false
        default: 'yarn'
      node-build-path:
        type: string
        default: .
      environment:
        type: string
        default: dev
      keystore_path:
        type: string
        default: android-keystore.jks
      flavor:
        type: string
        default: ''
      command:
        type: string
        default: assembleRelease
      enable-android:
        type: boolean
        default: false
      enable-ios:
        type: boolean
        default: true
    secrets:
      keystore-base64:
        required: false
      keystore-password:
        required: false
      keystore-alias:
        required: false
      keystore-path:
        required: false
      github-token:
        required: true
      p12-base64:
        required: false
      p12-password:
        required: false
      apple-api-key-id:
        required: false
      apple-api-issuer-id:
        required: false
      apple-api-key-content:
        required: false
      apple-team-id:
        required: false
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.setup-android.outputs.app-version }}
      app-name: ${{ steps.setup-android.outputs.app-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        id: setup-android
        uses: cvch29/platform-actions/.github/actions/shared-v2/setup-node@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          node-build-path: ${{ inputs.node-build-path }}

  build_android:
    needs: setup
    name: Build Android
    uses: cvch29/platform-workflows/.github/workflows/mobile-android-build.yml@main
    with:
      app-name: ${{ needs.setup.outputs.app-name }}
      command: ${{ inputs.command }}
      app-version: ${{ needs.setup.outputs.app-version }}
      # build-type: release
      # flavor: ${{ inputs.flavor }}
      technology: ${{ inputs.technology }}
      container-image-name-runner: "${{ vars.REGISTRY }}/android:${{ vars.CONTAINER_IMAGE_TAG_BUILD }}"
      container-image-resource-runner: "--cpus 6 -m 12g"
      sign: true
    secrets:
      keystore-base64: ${{ secrets.keystore-base64 }}
      keystore-password: ${{ secrets.keystore-password }}
      keystore-alias: ${{ secrets.keystore-alias }}
      keystore-path: ${{ secrets.keystore-path }}

  build_ios:
    needs: setup
    name: Build iOS
    uses: cvch29/platform-workflows/.github/workflows/mobile-ios-build.yml@main
    with:
      technology: ${{ inputs.technology }}
      app-version: ${{ needs.setup.outputs.app-version }}
      app-name: ${{ needs.setup.outputs.app-name }}
      scheme: ${{ needs.setup.outputs.app-name }}
      bundle-id: com.yourcompany.${{ needs.setup.outputs.app-name }}
    secrets:
      p12-base64: ${{ secrets.p12-base64 }}
      p12-password: ${{ secrets.p12-password }}
      provisioning-profile-base64: ${{ secrets.provisioning-profile-base64 }}
      apple-api-key-id: ${{ secrets.apple-api-key-id }}
      apple-api-issuer-id: ${{ secrets.apple-api-issuer-id }}
      apple-api-key-content: ${{ secrets.apple-api-key-content }}
      apple-team-id: ${{ secrets.apple-team-id }}

  scs:
    needs: [setup,build_android,build_ios]
    # name: Supply Chain Security
    uses: cvch29/platform-workflows/.github/workflows/shared-supply-chain-security.yml@main
    with:
      app-name: ${{ needs.setup.outputs.app-name }}
      artifact-path: "/__w/challenge-mbco/challenge-mbco/artifacts"
      container-image-name-runner: "${{ vars.REGISTRY }}/android:${{ vars.CONTAINER_IMAGE_TAG_SCS }}"
      container-image-resource-runner: "--cpus 2 -m 4g"

  artifact_release:
    needs: [setup, build_android, build_ios, scs]
    name: Artifact Release
    uses: cvch29/platform-workflows/.github/workflows/shared-release-tag.yml@main
    with:
      app-name: ${{ needs.setup.outputs.app-name }}
      app-version: ${{ needs.setup.outputs.app-version }}
      version-strategy: semver
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}