name: Mobile Android React Native Release

on:
  workflow_call:
    secrets:
      key_password:
        required: true
      keystore_password:
        required: true
      android_keystore_base64:
        required: true
    inputs:
      environment:
        type: string
        default: dev
      technology:
        type: string
        default: react-native
      keystore_path:
        type: string
        default: android-keystore.jks
      key_alias:
        type: string
        default: "keyAlias"
      app_version:
        required: true
        type: string
      app_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: write
  checks: write

# jobs:
#   build:
#     name: Build
#     runs-on: 
#       group: dso-linux
#     container:
#       image: localhost:5000/android:35-gradle7.3-jdk17
#       options: --cpus 8 -m 16g
#       volumes:
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/yarn:/opt/yarn
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/gradle/caches:/opt/gradle/caches
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/gradle/jdks:/opt/gradle/jdks
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/gradle/native:/opt/gradle/native
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/gradle/notifications:/opt/gradle/notifications
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/gradle/project-cache:/opt/gradle/project-cache
#         - /opt/repos/dev/${{ github.repository }}/${{ github.ref_name }}/node_modules:/workspace/node_modules
#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Dependencies
#         uses: cvch29/platform-actions/.github/actions/tooling/node@main
#         with:
#           working-directory: .

#       - name: Android build
#         uses: cvch29/platform-actions/.github/actions/domains/mobile/android/build@main
#         with:
#           keystore_path: ${{ inputs.keystore_path }}
#           store_password: ${{ secrets.keystore_password }}
#           key_alias: ${{ inputs.key_alias }}
#           key_password: ${{ secrets.key_password }}
#           keystore_base64: ${{ secrets.android_keystore_base64 }}

#       - name: Artifact Management
#         uses: cvch29/platform-actions/.github/actions/shared/artifact-manage@main
#         with:
#           app_name: ${{ inputs.app_name }}
#           app_version: ${{ inputs.app_version }}
#           path: android/app/build/outputs
#           pattern: |
#             apk/release/*.apk
#             bundle/release/*.aab
#             remote-config/config.json
#           name: android-release-files
#           retention-days: 1
#           if-no-files-found: warn
#           compression-level: 6
#           upload_path: |
#             android/app/build/outputs/apk/release/*.apk
#             android/app/build/outputs/bundle/release/*.aab
#             android/remote-config/*.json


jobs:
  build:
    name: Build
    runs-on:
      group: dso-linux

    env:
      GRADLE_USER_HOME: /tmp/gradle-${{ github.run_id }}-${{ github.run_attempt }}
      # Metro cache
      METRO_CACHE: /tmp/metro-cache

      # Node memory (IMPORTANTE)
      NODE_OPTIONS: --max-old-space-size=8192

    container:
      image: localhost:5000/android:35-gradle7.3-jdk17
      options: --cpus 8 -m 16g
      volumes:
        # Yarn cache
        - /opt/cache/yarn:/opt/yarn

        # Shared gradle dependency cache
        - /opt/cache/gradle/modules-2:/opt/gradle-shared/modules-2

        # Shared transforms cache
        - /opt/cache/gradle/transforms-3:/opt/gradle-shared/transforms-3

        # Shared build cache
        - /opt/cache/gradle/build-cache-1:/opt/gradle-shared/build-cache-1

        # Shared wrapper cache
        - /opt/cache/gradle/wrapper:/opt/gradle-shared/wrapper

        # Metro cache
        - /opt/cache/metro:/tmp/metro-cache
        # C++ cache (RN native libs)
        - /opt/cache/cxx:/workspace/android/.cxx
    steps:
      - uses: actions/checkout@v4

      - name: Restore shared gradle cache
        run: |
          mkdir -p $GRADLE_USER_HOME/caches
          mkdir -p $GRADLE_USER_HOME/wrapper

          ln -snf /opt/gradle-shared/modules-2 \
            $GRADLE_USER_HOME/caches/modules-2

          ln -snf /opt/gradle-shared/transforms-3 \
            $GRADLE_USER_HOME/caches/transforms-3

          ln -snf /opt/gradle-shared/build-cache-1 \
            $GRADLE_USER_HOME/caches/build-cache-1

          ln -snf /opt/gradle-shared/wrapper \
            $GRADLE_USER_HOME/wrapper/dists

      - name: Install Dependencies
        uses: cvch29/platform-actions/.github/actions/tooling/node@main
        with:
          working-directory: .

      - name: Android build
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/build@main
        with:
          keystore_path: ${{ inputs.keystore_path }}
          store_password: ${{ secrets.keystore_password }}
          key_alias: ${{ inputs.key_alias }}
          key_password: ${{ secrets.key_password }}
          keystore_base64: ${{ secrets.android_keystore_base64 }}

      - name: Artifact Management
        uses: cvch29/platform-actions/.github/actions/shared/artifact-manage@main
        with:
          app_name: ${{ inputs.app_name }}
          app_version: ${{ inputs.app_version }}
          path: android/app/build
          pattern: |
            outputs/apk/release/*.apk
            outputs/bundle/release/*.aab
            outputs/remote-config/config.json
            reports/profile/*.html
          name: android-release-files
          retention-days: 1
          if-no-files-found: warn
          compression-level: 6
          upload_path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/bundle/release/*.aab
            android/remote-config/*.json
            android/build/reports/profile/*.html

  artifact_release:
    name: Artifact Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: cvch29/platform-actions/.github/actions/shared/artifact-download@main
        with:
          artifact_name: android-release-files
          download_path: ./artifacts

      - name: Artifact Release
        uses: cvch29/platform-actions/.github/actions/shared/artifact-release-tag@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          app-version: ${{ inputs.app_version }}

  # distribute:
  #   name: Distribute
  #   needs: [build, artifact_release]
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: ${{ inputs.environment }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Download Artifacts
  #       uses: cvch29/platform-actions/.github/actions/shared/artifact-download@main
  #       with:
  #         artifact_name: android-release-files
  #         download_path: ./artifacts

  #     - name: Distribute to Firebase App Distribution
  #       uses: cvch29/platform-actions/.github/actions/domains/mobile/android/distribute/firebase-app@main
  #       with:
  #         app_id: 1:432490436563:android:fee35c44f2f2ccf59b4126
  #         apk_path: "artifacts/android/app/build/outputs/apk/release/${{ inputs.app_name }}-${{ inputs.app_version }}.apk"
  #         release_notes: 'Automated distribution from GitHub Actions'

  #     - name: Artifact Release
  #       uses: cvch29/platform-actions/.github/actions/shared/artifact-release-tag@main
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         app-version: ${{ inputs.app_version }}