name: 'Mobile Android — Build'

on:
  workflow_call:
    inputs:
      technology:
        description: 'react-native | native'
        type: string
        required: true
        default: 'native'
      app-name:
        type: string
        required: true
      app-version:
        type: string
        required: true
      sign:
        type: boolean
        required: false
        default: true
      command:
        type: string
        required: false
        default: assembleRelease
      container-image-name-runner:
        type: string
        required: false
        default: 'registry/android:latest'
      container-image-resource-runner:
        type: string
        required: false
        default: '--cpus 2 -m 4g' 
      enable-android:
        type: boolean
        required: false
        default: false
    secrets:
      keystore-base64:
        required: false
      keystore-password:
        required: false
      keystore-alias:
        required: false
      keystore-path:
        required: false
jobs:
  build:
    if: success() && (inputs.enable-android == true)
    name: Build Android
    runs-on:
      group: dso-linux
    env:
      GRADLE_USER_HOME: /tmp/gradle-${{ github.run_id }}-${{ github.run_attempt }}
      METRO_CACHE: /tmp/metro-cache
      NODE_OPTIONS: --max-old-space-size=8192
    container:
      image: ${{ inputs.container-image-name-runner }}
      options: ${{ inputs.container-image-resource-runner }}
      volumes:
        - /opt/cache/yarn:/opt/yarn
        - /opt/cache/gradle/modules-2:/opt/gradle-shared/modules-2
        - /opt/cache/gradle/transforms-3:/opt/gradle-shared/transforms-3
        - /opt/cache/gradle/build-cache-1:/opt/gradle-shared/build-cache-1
        - /opt/cache/gradle/wrapper:/opt/gradle-shared/wrapper
        - /opt/cache/metro:/tmp/metro-cache
        - /opt/cache/cxx:/workspace/.cxx
    steps:
      - uses: actions/checkout@v4

      - name: Restore shared gradle cache
        run: |
          mkdir -p $GRADLE_USER_HOME/caches
          mkdir -p $GRADLE_USER_HOME/wrapper

          ln -snf /opt/gradle-shared/modules-2 \
            $GRADLE_USER_HOME/caches/modules-2

          ln -snf /opt/gradle-shared/transforms-3 \
            $GRADLE_USER_HOME/caches/transforms-3

          ln -snf /opt/gradle-shared/build-cache-1 \
            $GRADLE_USER_HOME/caches/build-cache-1

          ln -snf /opt/gradle-shared/wrapper \
            $GRADLE_USER_HOME/wrapper/dists

      - name: Install Dependencies
        if: ${{ inputs.technology == 'react-native' }}
        uses: cvch29/platform-actions/.github/actions/tooling/node@main
        with:
          working-directory: .

      - name: Setup Keystore
        if: ${{ inputs.sign }}
        uses: cvch29/platform-actions/.github/actions/shared-v2/setup-certificate@main
        with:
          certificate-base64: ${{ secrets.keystore-base64 }}
          certificate-file: ${{ secrets.keystore-path }}

      - name: Android build
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/build@main
        with:
          command: ${{ inputs.command }}
          keystore-alias: ${{ secrets.keystore-alias }}
          keystore-password: ${{ secrets.keystore-password }}
          keystore-path: ${{ secrets.keystore-path }}

      - name: Artifact Management
        uses: cvch29/platform-actions/.github/actions/shared/artifact-manage@main
        with:
          app_name: ${{ inputs.app-name }}
          app_version: ${{ inputs.app-version }}
          path: android/app
          pattern: |
            build/outputs/apk/release/*.apk
            build/outputs/bundle/release/*.aab
            build/outputs/remote-config/config.json
            build/reports/profile/*.html
          name: android-release-files
          retention-days: 1
          if-no-files-found: warn
          compression-level: 6
          upload_path: |
            apk/release/${{ inputs.app-name }}-${{ inputs.app-version }}.apk
            bundle/release/${{ inputs.app-name }}-${{ inputs.app-version }}.aab
            remote-config/${{ inputs.app-name }}-${{ inputs.app-version }}.json
            build/reports/profile/${{ inputs.app-name }}-${{ inputs.app-version }}.html
            lockfile/gradle.lockfile