name: Mobile Release

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: dev
      deploy:
        type: boolean
        default: false

    secrets:
      key_password:
        required: true
      keystore_password:
        required: true
      android_keystore_base64:
        required: true

permissions:
  contents: write
  id-token: write

jobs:

  build:
    uses: cvch29/platform-workflows/.github/workflows/mobile-build.yml@main
    secrets:
      key_password: ${{ secrets.key_password }}
      keystore_password: ${{ secrets.keystore_password }}
      android_keystore_base64: ${{ secrets.android_keystore_base64 }}

  release:
    needs: build
    uses: cvch29/platform-workflows/.github/workflows/mobile-artifact-release.yml@main
    secrets: inherit

  distribute:
    if: inputs.deploy == true
    needs: build
    uses: cvch29/platform-workflows/.github/workflows/mobile-distribute.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit