name: 'Mobile React Native — Release'

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true
      platforms:
        description: 'android | ios | both'
        type: string
        required: false
        default: 'android'
      android-channel:
        type: string
        required: false
        default: 'play-internal'
      package-manager:
        type: string
        required: false
        default: 'yarn'
      gradle-build-path:
        type: string
        default: app/build.gradle.kts
      build-android:
        type: boolean
        required: false
        default: true
      build-ios:
        type: boolean
        required: false
        default: false
      environment:
        type: string
        default: dev
      technology:
        type: string
        default: react-native
      keystore_path:
        type: string
        default: android-keystore.jks
      flavor:
        type: string
        default: ''
    secrets:
      android-keystore-base64:
        required: false
      android-keystore-password:
        required: false
      android-key-alias:
        required: false
      android-key-password:
        required: false
      github-token:
        required: true

jobs:
  # security:
  #   uses: cvch29/platform-workflows/.github/workflows/shared-security-scan.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #     language: javascript
  #     run-codeql: true
  #     run-sca: true
  #     run-secrets: true
  #     run-sast: true
  #   permissions:
  #     contents: read
  #     security-events: write

  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.setup_android.outputs.app-version }}
      app-name: ${{ steps.setup_android.outputs.app-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        id: setup_android
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-gradle-path: ${{ inputs.gradle-build-path }}


  build_android:
    if: ${{ vars.ENABLE_ANDROID_BUILD == 'true' }}
    needs: setup
    name: Build
    uses: cvch29/platform-workflows/.github/workflows/mobile-android-build.yml@main
    with:
      app-name: ${{ needs.setup.outputs.app-name }}
      app-version: ${{ needs.setup.outputs.app-version }}
      build-type: release
      flavor: ${{ inputs.flavor }}
      sign: true
    secrets:
      keystore-base64: ${{ secrets.keystore-base64 }}
      keystore-password: ${{ secrets.keystore-password }}
      key-alias: ${{ secrets.key-alias }}
      key-password: ${{ secrets.key-password }}

  build_ios:
    if: ${{ vars.ENABLE_IOS_BUILD == 'true' }}
    needs: setup
    name: Build
    uses: cvch29/platform-workflows/.github/workflows/mobile-ios-build.yml@main
    with:
      app-name: ${{ needs.setup.outputs.app-name }}
      scheme: ${{ inputs.app-name }}
      bundle-id: com.yourcompany.${{ needs.setup.outputs.app-name }}
    secrets:
      p12-base64: ${{ secrets.p12-base64 }}
      p12-password: ${{ secrets.p12-password }}
      provisioning-profile-base64: ${{ secrets.provisioning-profile-base64 }}
  # quality-gate:
  #   needs: [build-android]
  #   if: always() && needs.build-android.result != 'failure'
  #   uses: cvch29/platform-workflows/.github/workflows/shared-quality-gates.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #     environment: staging
  #     require-sbom: true

  # tag:
  #   name: Tag Release
  #   needs: build-android
  #   uses: cvch29/platform-workflows/.github/workflows/shared-release-tag.yml@main
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #   secrets:
  #     github-token: ${{ secrets.github-token }}
