name: Mobile Android React Native CI/CD

on:
  workflow_call:
    secrets:
      key_password:
        required: true
      keystore_password:
        required: true
      android_keystore_base64:
        required: true
    inputs:
      deploy:
        type: boolean
        default: false
      environment:
        type: string
        default: dev
      gradle-build-path:
        type: string
        default: app/build.gradle.kts
      keystore_path:
        type: string
        default: android-keystore.jks
      key_alias:
        type: string
        default: "keyAlias"

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: write
  checks: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.setup_android.outputs.app_version }}
      app_name: ${{ steps.setup_android.outputs.app_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        id: setup_android
        uses: cvch29/platform-actions/.github/actions/domains/mobile/android-native/setup@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          build-gradle-path: ${{ inputs.gradle-build-path }}

  release:
    name: Release Workflow
    needs: setup
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/mobile-react-native-release.yml
    with:
      app_version: ${{ needs.setup.outputs.app_version }}
      app_name: ${{ needs.setup.outputs.app_name }}
      environment: ${{ inputs.environment }}
    secrets:
      key_password: ${{ secrets.key_password }}
      keystore_password: ${{ secrets.keystore_password }}
      android_keystore_base64: ${{ secrets.android_keystore_base64 }}

  pr_checks:
    name: PR Checks
    needs: setup
    if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/mobile-react-native-pr.yml