name: 'Shared — Supply Chain Security'

on:
  workflow_call:
    inputs:
      app-name:
        type: string
        required: true
      artifact-path:
        type: string
        required: false
        default: '.'
      image:
        type: string
        required: false
        default: ''
      generate-provenance:
        type: boolean
        required: false
        default: true
      storage-account:
        type: string
        required: false
        default: ''
      container-image-name-runner:
        type: string
        required: false
        default: ''
      container-image-resource-runner:
        type: string
        required: false
        default: '--cpus 2 -m 4g' 
    # outputs:
    #   sbom-path:
    #     value: ${{ jobs.generate.outputs.sbom-path }}
    #   component-count:
    #     value: ${{ jobs.generate.outputs.component-count }}

jobs:
  scs:
    name: Supply Chain Security
    runs-on:
      group: dso-linux
    container:
      image: ${{ inputs.container-image-name-runner }}
      options: ${{ inputs.container-image-resource-runner }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    outputs:
      sbom-path: ${{ steps.sbom.outputs.sbom-path }}
      component-count: ${{ steps.sbom.outputs.component-count }}
    steps:
      - uses: cvch29/platform-actions/.github/actions/shared/checkout@main
      - name: Download Artifacts
        uses: cvch29/platform-actions/.github/actions/shared/artifact-download@main
        with:
          artifact_name: android-release-files
          download_path: ./artifacts
      - name: Generate SBOM
        id: sbom
        uses: cvch29/platform-actions/.github/actions/governance/sbom@main
        with:
          artifact-path: ${{ inputs.artifact-path }}
          image: ${{ inputs.image }}
          format: 'cyclonedx-json,spdx-json'
          upload-artifact: true
      # - name: Attest build provenance
      #   if: inputs.generate-provenance
      #   uses: actions/attest-build-provenance@main
      #   with:
      #     subject-path: ${{ inputs.artifact-path }}
      # - name: Generate provenance attestation
      #   if: inputs.generate-provenance
      #   uses: cvch29/platform-actions/.github/actions/governance/provenance@main
      #   with:
      #     artifact-path: ${{ inputs.artifact-path }}
      #     artifact-name: ${{ inputs.app-name }}
      - uses: cvch29/platform-actions/.github/actions/governance/audit-log@main
        with:
          event-type: build
          environment: dev
          outcome: success
          app-name: ${{ inputs.app-name }}
          storage-account: ${{ inputs.storage-account }}
          metadata: '{"sbomComponents":"${{ steps.sbom.outputs.component-count }}"}'
