name: Android · Release

on:
  workflow_call:
    inputs:
      project:
        description: 'Nombre del proyecto/dominio (ej: android)'
        required: false
        type: string
        default: 'android'
      deploy_aab:
        description: 'Forzar compilación de AAB aunque el ambiente no sea producción'
        required: false
        type: boolean
        default: false
      envs_json_path:
        required: false
        type: string
        default: './.scripts/configs/envs.json'
      vault_path:
        description: >
          Path en Vault donde vive el secreto de la app. Default cubre el
          caso típico; cambiar solo si tu app usa un path distinto.
        required: false
        type: string
        default: 'apps-integradas/canales/ncd/aplicacion/frontend/android'
      env_keys:
        description: 'Keys del env info que quieras pasar a android-build. Formato "key:VAR" separadas por coma.'
        required: false
        type: string
        default: >-
          env:${{ vars.ENV }},
          env_name:${{ vars.ENV_NAME }},
          am_url:${{ vars.AM_URL }},
          api_url:${{ vars.API_URL }},
          realm_path:${{ vars.REALM_PATH }}
      vault_keys:
        description: 'Keys adicionales de Vault que quieras pasar a android-build o android-deploy-appcenter. Formato "key:VAR" separadas por coma.'
        required: false
        type: string
        default: >-
          ANDROID_STORE_PWD:ANDROID_STORE_PWD:text:base64,
          ANDROID_KEY_PWD:ANDROID_KEY_PWD:text:base64,
          DEXGUARD_KEY:DEXGUARD_KEY:text:base64,
          ANDROID_KEY_ALIAS:ANDROID_KEY_ALIAS,
          SSL_CERTIFICADO_IG:SSL_CERTIFICADO_IG:text:base64,
          FACEPHI_LICENSE:FACEPHI_LICENSE:text
    secrets:
      VAULT_ROLE_ID:
        required: true
      VAULT_SECRET_ID:
        required: true

jobs:
  release:
    runs-on: arc-mobile
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      # - name: "Test variables"
      #   run: |
      #     echo "Project: ${{ inputs.project }}"
      #     echo "Deploy AAB: ${{ inputs.deploy_aab }}"
      #     echo "Envs JSON Path: ${{ inputs.envs_json_path }}"
      #     echo "Vault Path: ${{ inputs.vault_path }}"
      #     echo "Env Keys: ${{ inputs.env_keys }}"
      #     echo "Vault Keys: ${{ inputs.vault_keys }}"

      - name: Resolver keys de Env
        id: env-keys
        uses: cvch29/platform-actions/actions/shared/resolve-envs-keys@main
        with:
          project: ${{ inputs.project }}
          envs_json_path: ${{ inputs.envs_json_path }} # Opcional, para casos se use un json de envs distinto al default.
          env_keys: ${{ inputs.env_keys }}

      # - name: Resolver keys de Vault
      #   id: vault-keys
      #   uses: cvch29/platform-actions/actions/shared/resolve-vault-keys@main
      #   with:
      #     project: ${{ inputs.project }}
      #     envs_json_path: ${{ inputs.envs_json_path }} # Opcional, para casos se use un json de vault distinto al default.
      #     vault_keys: ${{ inputs.vault_keys }}
      #     vault_path: ${{ inputs.vault_path }}

      - name: "Test resolved variables"
        run: |
          echo "Resolved Env Vars:"
          echo "${{ steps.env-keys.outputs.resolved-vars }}"
          # echo "Resolved Vault Vars:"
          # echo "${{ steps.vault-keys.outputs.resolved-vars }}"
          env